tribus/web/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright (C) 2013-2014 Tribus Developers
#
# This file is part of Tribus.
#
# Tribus is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Tribus is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.views.generic.base import TemplateView
from django.conf.urls import patterns, include, url
from django.contrib.admin import autodiscover

from tribus.web.api import api_01
from tribus.web.admin.sites import tribus_admin

autodiscover()

urlpatterns = patterns(
    '',
    url(regex=r'^$', view='tribus.web.views.index'),
    url(regex=r'^search/$', view='tribus.web.views.search'),
    url(regex=r'^about/$',
        view=TemplateView.as_view(template_name='about.html')),
    url(regex=r'^about/privacy/$',
        view=TemplateView.as_view(template_name='privacy.html')),
    url(regex=r'^about/terms/$',
        view=TemplateView.as_view(template_name='terms.html')),
    url(regex=r'', view=include('tribus.web.registration.urls')),
    url(regex=r'', view=include('tribus.web.cloud.urls')),
    url(regex=r'', view=include('tribus.web.profile.urls')),
    url(regex=r'^api/', view=include(api_01.urls)),
    url(regex=r'^admin/', view=include(tribus_admin.urls)),
)

tribus/web/user/urls.py
"""
Backwards-compatible URLconf for existing django-registration
installs; this allows the standard ``include('registration.urls')`` to
continue working, but that usage is deprecated and will be removed for
django-registration 1.0. For new installs, use
``include('registration.backends.default.urls')``.

"""

"""
URLconf for registration and activation, using django-registration's
default backend.

If the default behavior of these views is acceptable to you, simply
use a line like this in your root URLconf to set up the default URLs
for registration::

    (r'^accounts/', include('registration.backends.default.urls')),

This will also automatically set up the views in
``django.contrib.auth`` at sensible default locations.

If you'd like to customize registration behavior, feel free to set up
your own URL patterns for these views instead.

"""

from django.conf import settings
from django.conf.urls import patterns, url
from django.views.generic.base import TemplateView

from tribus.web.user.views import ActivationView, SignupView, LoginView
from tribus.web.user.forms import LoginForm, PasswordResetForm, PasswordChangeForm, SetPasswordForm


urlpatterns = patterns(
    '',

    url(regex=r'^login$',
        view=LoginView,
        kwargs={
            'template_name': 'user/login_form.html',
            'redirect_field_name': settings.LOGIN_REDIRECT_URL,
            'authentication_form': LoginForm
        },
        name='user_login',
    ),

    url(regex=r'^logout$',
        view='django.contrib.auth.views.logout',
        kwargs={
            'next_page': settings.LOGIN_REDIRECT_URL
        },
        name='user_logout'
    ),

    url(regex=r'^signup$',
        view=SignupView.as_view(template_name='user/signup_form.html'),
        name='user_signup',
    ),

    url(regex=r'^signup/complete$',
        view=TemplateView.as_view(template_name='user/signup_complete.html'),
        name='user_signup_complete',
    ),

    url(regex=r'^activate/key/(?P<activation_key>\w+)$',
        view=ActivationView.as_view(template_name='user/activate_form.html'),
        name='user_activate',
    ),

    url(regex=r'^activate/complete$',
        view=TemplateView.as_view(template_name='user/activate_complete.html'),
        name='user_activate_complete',
    ),

    url(regex=r'^password/change$',
        view='django.contrib.auth.views.password_change',
        kwargs={
            'template_name': 'user/password_change_form.html',
            'post_change_redirect': '/password/change/done',
            'password_change_form': PasswordChangeForm
        },
        name='user_password_change',
    ),

    url(regex=r'^password/change/done$',
        view='django.contrib.auth.views.password_change_done',
        kwargs={
            'template_name': 'user/password_change_done.html'
        },
        name='user_password_change_done',
    ),

    url(regex=r'^password/reset$',
        view='django.contrib.auth.views.password_reset',
        kwargs={
            'template_name': 'user/password_reset_form.html',
            'email_template_name': 'user/password_reset_email.txt',
            'subject_template_name': 'user/password_reset_subject.txt',
            'password_reset_form': PasswordResetForm,
            'post_reset_redirect': '/password/reset/done'
        },
        name='user_password_reset',
    ),

    url(regex=r'^password/reset/done$',
        view='django.contrib.auth.views.password_reset_done',
        kwargs={
            'template_name': 'user/password_reset_done.html'
        },
        name='user_password_reset_done',
    ),

    url(regex=r'^password/reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)$',
        view='django.contrib.auth.views.password_reset_confirm',
        kwargs={
            'template_name': 'user/password_reset_confirm.html',
            'set_password_form': SetPasswordForm,
            'post_reset_redirect': '/password/reset/complete'
        },
        name='user_password_reset_confirm',
    ),

    url(regex=r'^password/reset/complete$',
        view='django.contrib.auth.views.password_reset_complete',
        kwargs={
            'template_name': 'user/password_reset_complete.html'
        },
        name='user_password_reset_complete',
    ),

)

tribus/web/user/forms.py
"""
Forms and validation code for user registration.

Note that all of these forms assume Django's bundle default ``User``
model; since it's not possible for a form to anticipate in advance the
needs of custom user models, you will need to write your own forms if
you're using a custom model.

"""

import base64
import hashlib
import random
import string

from django import forms
from django.forms import Form
from django.utils.datastructures import SortedDict
from django.contrib.auth.forms import AuthenticationForm, PasswordResetForm as BasePasswordResetForm, SetPasswordForm as BaseSetPasswordForm
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

from tribus.web.user.models import LdapUser

class LoginForm(AuthenticationForm):
    """
    Subclass of Django ``AuthenticationForm`` which adds a remember me
    checkbox.
    """

    username = forms.RegexField(
                                    label = _('Username'), required = True,
                                    regex = r'^[\w.@+-]+$',
                                    widget = forms.TextInput(
                                        attrs= {
                                            'placeholder': _('Enter your username'),
                                            'class': 'input-block'
                                        }
                                    ),
                                    max_length = 30,
                                    error_messages = {
                                        'invalid': _("This value may contain only letters, numbers and @/./+/-/_ characters.")
                                    }
                                )

    password = forms.CharField(
                                    label = _('Password'), required = True,
                                    widget = forms.PasswordInput(
                                        attrs = {
                                            'placeholder': _('Enter your password'),
                                            'class': 'input-block'
                                        }
                                    )
                                )

    remember_me = forms.BooleanField(
                                        label = _('Remember my session'),
                                        initial = False,
                                        required = False
                                    )


class SignupForm(Form):
    """
    Form for registering a new user account.
    
    Validates that the requested username is not already in use, and
    requires the password to be entered twice to catch typos.
    
    Subclasses should feel free to add any additional validation they
    need, but should avoid defining a ``save()`` method -- the actual
    saving of collected user data is delegated to the active
    registration backend.

    """
    required_css_class = 'required'
    username = forms.RegexField(
                                    label = _('Username'), required = True,
                                    regex = r'^[\w.@+-]+$',
                                    widget = forms.TextInput(
                                        attrs = {
                                            'placeholder': _('Pick a username'),
                                            'class': 'input-block'
                                        }
                                    ),
                                    max_length = 30,
                                    error_messages = {
                                    'invalid': _("This value may contain only letters, numbers and @/./+/-/_ characters.")
                                    }
                                )

    first_name = forms.RegexField(
                                    label = _('First name'), required = True,
                                    regex = r'^[\w.@+-]+$',
                                    widget = forms.TextInput(
                                        attrs = {
                                            'placeholder': _('First name'),
                                            'class': 'input-block'
                                        }
                                    ),
                                    max_length = 30,
                                    error_messages = {
                                    'invalid': _("This value may contain only letters, numbers and @/./+/-/_ characters.")
                                    }
                                )

    last_name = forms.RegexField(
                                    label = _('Last name'), required = True,
                                    regex = r'^[\w.@+-]+$',
                                    widget = forms.TextInput(
                                        attrs = {
                                            'placeholder': _('Last name'),
                                            'class': 'input-block'
                                        }
                                    ),
                                    max_length = 30,
                                    error_messages = {
                                    'invalid': _("This value may contain only letters, numbers and @/./+/-/_ characters.")
                                    }
                                )

    email = forms.EmailField(
                                label = _('Email'), required = True,
                                widget = forms.TextInput(
                                    attrs = {
                                        'placeholder': _('Enter a valid email'),
                                        'class': 'input-block'
                                    }
                                ),
                                max_length=254
                            )

    password = forms.CharField(
                                    label = _('Password'), required = True,
                                    widget = forms.PasswordInput(
                                        attrs = {
                                            'placeholder': _('Create a password'),
                                            'class': 'input-block'
                                        }
                                    )
                                )


    def clean_username(self):
        """
        Validate that the username is alphanumeric and is not already
        in use.
        
        """
        existingldap = LdapUser.objects.filter(username=self.cleaned_data['username'])
        if existingldap.exists():
            raise forms.ValidationError(_("A user with that username already exists."))
        else:
            existingdb = User.objects.filter(username__iexact=self.cleaned_data['username'])
            if existingdb.exists():
                existingdb.delete()
            return self.cleaned_data['username']


class PasswordResetForm(BasePasswordResetForm):
    email = forms.EmailField(
                                label = _('Email'), required = True,
                                widget = forms.TextInput(
                                    attrs = {
                                        'placeholder': _('Enter a valid email'),
                                        'class': 'input-block'
                                    }
                                ),
                                max_length = 254
                            )


class SetPasswordForm(BaseSetPasswordForm):
    """
    A form that lets a user change set his/her password without entering the
    old password
    """
    new_password1 = forms.CharField(
                                    label = _('Password'), required = True,
                                    widget = forms.PasswordInput(
                                        attrs = {
                                            'placeholder': _('Create a new password'),
                                            'class': 'input-block'
                                        }
                                    )
                                )

    new_password2 = forms.CharField(
                                    label = _('Password (repeat)'), required = True,
                                    widget = forms.PasswordInput(
                                        attrs = {
                                            'placeholder': _('Repeat your new password'),
                                            'class': 'input-block'
                                        }
                                    )
                                )


#    def create_ldap_password(self, password, algorithm='SSHA', salt=None):
#        """
#        Encrypts a password as used for an ldap userPassword attribute.
#        """
#        s = hashlib.sha1()
#        s.update(password)

#        if algorithm == 'SSHA':
#            if salt is None:
#                salt = ''.join([random.choice(string.letters) for i in range(8)])

#            s.update(salt)
#            return '{SSHA}%s' % base64.encodestring(s.digest() + salt).rstrip()
#        else:
#            raise NotImplementedError


    def save(self, commit=True):

        try:
            u = LdapUser.objects.get(username=self.user.username)
        except LdapUser.DoesNotExist:
            raise forms.ValidationError(_("A user with that username already exists."))
        else:
            self.user.set_password(self.cleaned_data['new_password1'])

            if commit:
                self.user.save()

            u.password = self.user.password
            u.save()

            return self.user


class PasswordChangeForm(SetPasswordForm):
    """
    A form that lets a user change his/her password by entering
    their old password.
    """

    old_password = forms.CharField(
                                    label = _('Old password'), required = True,

tribus/data/templates/user/activate_form.html
{% extends "user/base.html" %}
{% block title %}Activation problem{% endblock %}
{% block content %}
<div class="well jumbotron">
	<div class="container">
	    <div class="hero-unit">
            <p>Oops &ndash; it seems that your activation key is invalid. Please check the url again.</p>
		</div>
	</div>
</div>
{% endblock %}

tribus/data/templates/user/login_form.html
{% extends 'user/base.html' %}
{% load i18n %}
{% block title %}{% trans "Log in" %}{% endblock %}
{% block content %}
<div class="well jumbotron">
	<div class="container">
        <div class="row-fluid">
	        <div class="span4">
		        <h3 class="lighter block">{% trans "Log in with" %}</h3>
	            <div class="row-fluid bigger-200">
	                <a href="{% url 'socialauth_begin' 'facebook' %}">
	                    <span class="span3 bigger-200 text-center blue">
	                        <i class="icon-facebook-sign"></i>
	                    </span>
	                </a>
	                <a href="{% url 'socialauth_begin' 'twitter' %}">
	                    <span class="span3 bigger-200 text-center light-blue">
	                        <i class="icon-twitter-sign"></i>
	                    </span>
	                </a>
	                <a href="{% url 'socialauth_begin' 'github' %}">
	                    <span class="span3 bigger-200 text-center dark">
	                        <i class="icon-github-sign"></i>
	                    </span>
	                </a>
	                <a href="{% url 'socialauth_begin' 'google-oauth2' %}">
	                    <span class="span3 bigger-200 text-center red">
	                        <i class="icon-google-plus-sign"></i>
	                    </span>
	                </a>
	            </div>
		        <h3 class="lighter block ">{% trans "- or -" %}</h3>
		        <form id="login-form" method="post" action="{% url 'user_login' %}">
                    {% csrf_token %}
                    <ul class="unstyled">
                        <li>{{ form.username }}</li>
                        <li>{{ form.password }}</li>
                        <li>
                            <label for="id_remember_me">
                                {{ loginform.remember_me }}
                                <span class="lbl">
                                     {{ loginform.remember_me.label }}
                                </span>
                            </label>
                        </li>
                    </ul>
			        <button class="btn btn-yellow btn-block" type="submit">{% trans "Log in" %}</button>
			        <input type="hidden" name="next" value="{{ next }}" />
		        </form>
		        <ul class="unstyled">
			        <li><a href="{% url 'user_password_reset' %}">{% trans "forgot your password?" %}</a></li>
			        <li><a href="{% url 'user_signup' %}">{% trans "are you new to Tribus?" %}</a></li>
		        </ul>
		    </div>
		    <div class="span7 offset1">
                {% include 'user/form_errors.html' %}
		    </div>
		</div>
	</div>
</div>
{% endblock %}

tribus/data/templates/user/password_change_done.html
{% extends "user/base.html" %}
{% block title %}Password changed{% endblock %}
{% block content %}
<div class="well jumbotron">
	<div class="container">
		{% include "user/password_change_done_text.html" %}
	</div>
</div>
{% endblock %}

tribus/data/templates/user/password_change_form.html
{% extends "user/base.html" %}
{% block title %}Change password{% endblock %}
{% block content %}
<div class="well jumbotron">
	<div class="container">
			{% include "user/password_change_form_datos.html" %}
	</div>
</div>
{% endblock %}

tribus/data/templates/user/password_change_form_datos.html
<div class="row-fluid">
	<div class="span4">
	    <h4 class="lighter block blue">Change password</h4>
	    <hr />
	    <p>Después de introducir sus datos de usuario, usted podrá editar su información de perfil.</p>|
	    <form method="post" action="{% url 'user_password_change' %}">
	        {% csrf_token %}
	        <ul class="unstyled">
		        {% for field in form %}
	    			<li>{{ field }}</li>
				{% endfor %}
	        </ul>
	        <button class="btn btn-yellow btn-block" type="submit">Change password</button>
	        <input type="hidden" name="next" value="{{ next }}" />
	    </form>
	</div>
    <div class="span1"></div>
    <div class="span7">
        {% include 'user/form_errors.html' %}
    </div>	    
	</div>
</div>

tribus/data/templates/user/password_reset_complete.html
{% extends "user/base.html" %}
{% block title %}Password reset complete{% endblock %}
{% block content %}
<div class="well jumbotron">
	<div class="container">
	    <div class="hero-unit">
            <p>Your password has been reset! You may now <a href="{% url 'user_login' %}">log in</a>.</p>
		</div>
	</div>
</div>
{% endblock %}

tribus/data/templates/user/password_reset_confirm.html
{% extends "user/base.html" %}
{% block title %}Confirm password reset{% endblock %}
{% block content %}
<div class="well jumbotron">
	<div class="container">
        <div class="row-fluid">
	        <div class="span4">
		        <h3 class="lighter block blue">Reset your password</h3>
		        <hr />
                <p>Enter your new password below to reset your password:</p>
                {% if form.errors %}
		        <div class="alert alert-error">
		        	<strong>
				        <i class="icon-remove"></i> Oh snap!
			        </strong>
					<p>The operation could not be performed because one or more error(s) occurred. Please resubmit the form after making the following changes:</p>
					<ul>
			        {% if form.non_field_errors %}
                		{% for non_field_error in form.non_field_errors %}
                			<li>{{ non_field_error|striptags }}</li>
                		{% endfor %}
			        {% endif %}
			        {% for field in form %}
				        {% if field.errors %}
                			<li><strong>{{ field.label }}</strong> {{ field.errors|striptags }}</li>
                		{% endif %}
		            {% endfor %}
					</ul>
		        </div>
		        {% endif %}
                	<form method="post" action="">
                    {% csrf_token %}
                    <ul class="unstyled">
				        {% for field in form %}
                			<li>{{ field }}</li>
            			{% endfor %}
                    </ul>
			        <button class="btn btn-yellow btn-block" type="submit">Set password</button>
			        <input type="hidden" name="next" value="{{ next }}" />
		        </form>
		    </div>
	        <div class="span1"></div>
	        <div class="span7 hero-unit">
                <p>algo aquí</p>
		    </div>
	    </div>
	</div>
</div>
{% endblock %}

tribus/data/templates/user/password_reset_done.html
{% extends "user/base.html" %}
{% block title %}Password reset{% endblock %}
{% block content %}
<div class="well jumbotron">
	<div class="container">
	    <div class="hero-unit">
            <p>We have sent you an email with a link to reset your password. Please check your email and click the link to continue.</p>
		</div>
	</div>
</div>
{% endblock %}

tribus/data/templates/user/password_reset_form.html
{% extends "user/base.html" %}
{% block title %}Reset password{% endblock %}
{% block content %}
<div class="well jumbotron">
	<div class="container">
        <div class="row-fluid">
	        <div class="span4">
		        <h3 class="lighter block blue">Reset your password</h3>
		        <hr />
                <p>Forgot your password?  Enter your email in the form below and we'll send you instructions for creating a new one.</p>
                <form method="post" action="{% url 'user_password_reset' %}">
                    {% csrf_token %}
                    <ul class="unstyled">
				        {% for field in form %}
                			<li>{{ field }}</li>
            			{% endfor %}
                    </ul>
			        <button class="btn btn-yellow btn-block" type="submit">Reset password</button>
			        <input type="hidden" name="next" value="{{ next }}" />
		        </form>
		    </div>
	        <div class="span1"></div>
		    <div class="span7">
                {% include 'user/form_errors.html' %}
		    </div>
	    </div>
	</div>
</div>
{% endblock %}

tribus/data/templates/user/signup_complete.html
{% extends "user/base.html" %}
{% block title %}Activation email sent{% endblock %}
{% block content %}
<div class="well jumbotron">
	<div class="container">
	    <div class="hero-unit">
            <p>An activation email has been sent. Please check your email and click on the link to activate your account.</p>
		</div>
	</div>
</div>
{% endblock %}

tribus/data/templates/user/signup_form.html
{% extends "user/base.html" %}
{% block title %}Sign up for an account{% endblock %}
{% block content %}
<div class="well jumbotron">
	<div class="container">
        <div class="row-fluid">
	        <div class="span4">
		        <h3 class="lighter block blue">Sign up to Tribus</h3>
		        <hr />
		        <p>Después de introducir sus datos de usuario, usted podrá editar su información de perfil.</p>
		        <form method="post" action="{% url 'user_signup' %}">
                    {% csrf_token %}
                    <ul class="unstyled">
                        <li>{{ form.username }}</li>
                        <li class="row-fluid">
                            <span class="span6">{{ form.first_name }}</span>
                            <span class="span6">{{ form.last_name }}</span>
                        </li>
                        <li>{{ form.email }}</li>
                        <li>{{ form.password }}</li>
                    </ul>
			        <button class="btn btn-yellow btn-block" type="submit">Sign up</button>
			        <input type="hidden" name="next" value="{{ next }}" />
		        </form>
	        </div>
		    <div class="span1"></div>
		    <div class="span7">
                {% include 'user/form_errors.html' %}
		    </div>
	    </div>
	</div>
</div>
{% endblock %}