tribus/web/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright (C) 2013-2014 Tribus Developers
#
# This file is part of Tribus.
#
# Tribus is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Tribus is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.views.generic.base import TemplateView
from django.conf.urls import patterns, include, url
from django.contrib.admin import autodiscover

from tribus.web.api import api_01
from tribus.web.admin.sites import tribus_admin

autodiscover()

urlpatterns = patterns(
    '',
    url(regex=r'^$', view='tribus.web.views.index'),
    url(regex=r'^search/$', view='tribus.web.views.search'),
    url(regex=r'^about/$',
        view=TemplateView.as_view(template_name='about.html')),
    url(regex=r'^about/privacy/$',
        view=TemplateView.as_view(template_name='privacy.html')),
    url(regex=r'^about/terms/$',
        view=TemplateView.as_view(template_name='terms.html')),
    url(regex=r'', view=include('tribus.web.registration.urls')),
    url(regex=r'', view=include('tribus.web.cloud.urls')),
    url(regex=r'', view=include('tribus.web.profile.urls')),
    url(regex=r'^api/', view=include(api_01.urls)),
    url(regex=r'^admin/', view=include(tribus_admin.urls)),
)

tribus/web/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright (C) 2013-2014 Tribus Developers
#
# This file is part of Tribus.
#
# Tribus is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Tribus is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


from django.db import models
from django.contrib.auth.models import User


class Trib(models.Model):
    user_id = models.ForeignKey(User, verbose_name='')
    trib_pub_date = models.DateTimeField(blank=False)
    trib_content = models.CharField("", max_length=200, blank=False)


class Comment(models.Model):
    user_id = models.ForeignKey(User, verbose_name='')
    trib_id = models.ForeignKey("Trib", verbose_name='')
    comment_content = models.CharField("", max_length=200, blank=False)
    comment_pub_date = models.DateTimeField("", blank=False)

tribus/data/templates/about.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans "About" %}{% endblock %}
{% block content %}
<div class="jumbotron">
    <div class="container-fluid">
        <div class="row-fluid dashboard_container">
            <div class="span8 dashboard_timeline">
                <div class="trib_list">
                    <ul>
                        <li class="trib_intro">
                            <span class="trib_body">
                                <span class="trib_title">
                                    <h2>{% trans 'Tribus' %}</h2>
                                </span>
                                <span class="trib_content">
                                    <p>{% blocktrans %}Tribus is a social network for managing open source software communities. Its goal is to simplify the tedious and repetitive maintenance tasks, while making available to its members the best tools to express their creativity and develop the full potential of their abilities.{% endblocktrans %}</p>
                                    <p>{% blocktrans %}Tribus promotes self-management and responsibility in various areas of software production process, establishing an organizational model that allows progression and natural rotation of roles.{% endblocktrans %}</p>
                                    <h3>{% trans 'More information' %}</h3>
                                    <p>
                                        <ul>
                                            <li>
                                                <strong>{% trans 'Source code:' %}</strong>
                                                <a href="http://github.com/tribusdev/tribus" target="_blank">
                                                    github.com/tribusdev/tribus
                                                </a>
                                            </li>
                                            <li>
                                                <strong>{% trans 'Ticket system:' %}</strong>
                                                <a href="http://github.com/tribusdev/tribus/issues" target="_blank">
                                                    github.com/tribusdev/tribus/issues
                                                </a></li>
                                            <li>
                                                <strong>{% trans 'Documentation:' %}</strong>
                                                <a href="http://tribus.readthedocs.org/" target="_blank">
                                                    tribus.readthedocs.org
                                                </a></li>
                                            <li>
                                                <strong>{% trans 'Translation:' %}</strong>
                                                <a href="http://www.transifex.com/projects/p/tribus/" target="_blank">
                                                    transifex.com/projects/p/tribus
                                                </a></li>
                                            <li>
                                                <strong>{% trans 'Twitter:' %}</strong>
                                                <a href="http://twitter.com/tribusdev" target="_blank">
                                                    twitter.com/tribusdev
                                                </a></li>
                                            <li>
                                                <strong>{% trans 'Facebook:' %}</strong>
                                                <a href="http://www.facebook.com/groups/tribusdev" target="_blank">
                                                    facebook.com/groups/tribusdev
                                                </a></li>
                                        </ul>
                                    </p>
                                    
                                </span>
                            </span>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="span4 dashboard_panel">
                <a href="/" class="btn btn-block btn-success btn-large">
                    <span class="bigger-140 width-100 block">
                        <i class="fa fa-chevron-left"></i>
                        {% trans 'Go back' %}
                    </span>
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

tribus/data/templates/angular-bootstrap-templates.html
<script type="text/ng-template" id="template/accordion/accordion-group.html">
	<div class="accordion-group">
  		<div class="accordion-heading" ><a class="accordion-toggle" ng-click="isOpen = !isOpen" accordion-transclude="heading"> {% verbatim %} {{heading}} {% endverbatim %}</a></div>
  		<div class="accordion-body" collapse="!isOpen">
    	<div class="accordion-inner" ng-transclude></div></div>
	</div>
</script>

<script type="text/ng-template" id="template/accordion/accordion.html">
	<div class="accordion" ng-transclude></div>
</script>

<script type="text/ng-template" id="template/alert/alert.html">
	<div class='alert' ng-class='type && "alert-" + type'>
    	<button ng-show='closeable' type='button' class='close' ng-click='close()'>&times;</button>
    	<div ng-transclude></div>
	</div>
</script>

<script type="text/ng-template" id="template/carousel/carousel.html">
	<div ng-mouseenter="pause()" ng-mouseleave="play()" class="carousel">
	    <ol class="carousel-indicators" ng-show="slides().length > 1">
	        <li ng-repeat="slide in slides()" ng-class="{active: isActive(slide)}" ng-click="select(slide)"></li>
	    </ol>
	    <div class="carousel-inner" ng-transclude></div>
	    <a ng-click="prev()" class="carousel-control left" ng-show="slides().length > 1">&lsaquo;</a>
	    <a ng-click="next()" class="carousel-control right" ng-show="slides().length > 1">&rsaquo;</a>
	</div>
</script>

<script type="text/ng-template" id="template/carousel/slide.html">
	<div ng-class="{
	    'active': leaving || (active && !entering),
	    'prev': (next || active) && direction=='prev',
	    'next': (next || active) && direction=='next',
	    'right': direction=='prev',
	    'left': direction=='next'
	  }" class="item" ng-transclude></div>
</script>

<script type="text/ng-template" id="template/datepicker/datepicker.html">
	<table>
		<thead>
			<tr class="text-center">
		  		<th><button type="button" class="btn pull-left" ng-click="move(-1)"><i class="fa fa-chevron-left"></i></button></th>
		  		<th colspan="{% verbatim %} {{rows[0].length - 2 + showWeekNumbers}} {% endverbatim %}"><button type="button" class="btn btn-block" ng-click="toggleMode()"><strong>{% verbatim %} {{title}} {% endverbatim %}</strong></button></th>
		  		<th><button type="button" class="btn pull-right" ng-click="move(1)"><i class="fa fa-chevron-right"></i></button></th>
			</tr>
			<tr class="text-center" ng-show="labels.length > 0">
			  	<th ng-show="showWeekNumbers">#</th>
			  	<th ng-repeat="label in labels">{% verbatim %} {{label}} {% endverbatim %}</th>
			</tr>
		</thead>
	  	<tbody>
			<tr ng-repeat="row in rows">
			  	<td ng-show="showWeekNumbers" class="text-center"><em>{% verbatim %} {{ getWeekNumber(row) }} {% endverbatim %}</em></td>
				<td ng-repeat="dt in row" class="text-center">
					<button type="button" style="width:100%;" class="btn" ng-class="{'btn-info': dt.selected}" ng-click="select(dt.date)" ng-disabled="dt.disabled"><span ng-class="{muted: dt.secondary}">{% verbatim %} {{dt.label}} {% endverbatim %}</span></button>
			  	</td>
			</tr>
	  </tbody>
	</table>
</script>

<script type="text/ng-template" id="template/datepicker/popup.html">
	<ul class="dropdown-menu" ng-style="{display: (isOpen && 'block') || 'none', top: position.top+'px', left: position.left+'px'}">
	    <li ng-transclude></li>
	    <li ng-show="showButtonBar" style="padding:10px 9px 2px">
            <span class="btn-group">
                <button type="button" class="btn btn-small btn-inverse" ng-click="today()">{% verbatim %} {{currentText}} {% endverbatim %}</button>
                <button type="button" class="btn btn-small btn-info" ng-click="showWeeks = ! showWeeks" ng-class="{active: showWeeks}">{% verbatim %} {{toggleWeeksText}} {% endverbatim %}</button>
                <button type="button" class="btn btn-small btn-danger" ng-click="clear()">{% verbatim %} {{clearText}} {% endverbatim %}</button>
            </span>
            <button type="button" class="btn btn-small btn-success pull-right" ng-click="isOpen = false">{% verbatim %} {{closeText}} {% endverbatim %}</button>
	    </li>
	</ul>
</script>

<script type="text/ng-template" id="template/modal/backdrop.html">
	<div class="modal-backdrop fade" ng-class="{in: animate}" ng-style="{'z-index': 1040 + index*10}" ng-click="close($event)"></div>
</script>

<script type="text/ng-template" id="template/modal/window.html">
	<div class="modal fade {% verbatim %} {{ windowClass }} {% endverbatim %}" ng-class="{in: animate}" ng-style="{'z-index': 1050 + index*10}" ng-transclude></div>
</script>

<script type="text/ng-template" id="template/pagination/pager.html">
	<div class="pager">
		<ul>
	    	<li ng-repeat="page in pages" ng-class="{disabled: page.disabled, previous: page.previous, next: page.next}"><a ng-click="selectPage(page.number)"> {% verbatim %}{{page.text}}{% endverbatim %}</a></li>
	  	</ul>
	</div>
</script>

<script type="text/ng-template" id="template/pagination/pagination.html">
<div class="pagination"><ul>
  	<li ng-repeat="page in pages" ng-class="{active: page.active, disabled: page.disabled}"><a ng-click="selectPage(page.number)">{% verbatim %}{{page.text}}{% endverbatim %}</a></li>
  	</ul>
</div>
</script>

<script type="text/ng-template" id="template/popover/popover.html">
	<div class="popover {% verbatim %}{{placement}}{% endverbatim %}" ng-class="{ in: isOpen(), fade: animation() }">
	  <div class="arrow"></div>
	  <div class="popover-inner">
	      <h3 class="popover-title" ng-bind="title" ng-show="title"></h3>
	      <div class="popover-content" ng-bind="content"></div>
	  </div>
	</div>
</script>

<script type="text/ng-template" id="template/progressbar/bar.html">
	<div class="bar" ng-class="type && 'bar-' + type" ng-transclude></div>
</script>

<script type="text/ng-template" id="template/progressbar/progress.html">
	<div class="progress" ng-transclude></div>
</script>

<script type="text/ng-template" id="template/progressbar/progressbar.html">
	<div class="progress"><div class="bar" ng-class="type && 'bar-' + type" ng-transclude></div></div>
</script>

<script type="text/ng-template" id="template/rating/rating.html">
	<span ng-mouseleave="reset()">
        <i ng-repeat="r in range" ng-mouseenter="enter($index + 1)" ng-click="rate($index + 1)" ng-class="$index < val && (r.stateOn || 'fa fa-star') || (r.stateOff || 'fa fa-star-o')"></i>
	</span>
</script>

<script type="text/ng-template" id="template/tabs/tab.html">
	<li ng-class="{active: active, disabled: disabled}">
  		<a ng-click="select()" tab-heading-transclude>{% verbatim %}{{heading}}{% endverbatim %}</a>
	</li>
</script>

<script type="text/ng-template" id="template/tabs/tabset-titles.html">
	<ul class="nav {% verbatim %}{{type && 'nav-' + type}}{% endverbatim %}" ng-class="{'nav-stacked': vertical}">
	</ul>
</script>

<script type="text/ng-template" id="template/tabs/tabset.html">
	<div class="tabbable" ng-class="{'tabs-right': direction == 'right', 'tabs-left': direction == 'left', 'tabs-below': direction == 'below'}">
	  <div tabset-titles="tabsAbove"></div>
	  <div class="tab-content">
	    <div class="tab-pane" 
	         ng-repeat="tab in tabs" 
	         ng-class="{active: tab.active}"
	         tab-content-transclude="tab">
	    </div>
	  </div>
	  <div tabset-titles="!tabsAbove"></div>
	</div>
</script>

<script type="text/ng-template" id="template/timepicker/timepicker.html">
	<table class="form-inline">
	    <tr class="text-center">
            <td><a ng-click="incrementHours()" class="btn btn-link"><i class="fa fa-chevron-up"></i></a></td>
            <td>&nbsp;</td>
            <td><a ng-click="incrementMinutes()" class="btn btn-link"><i class="fa fa-chevron-up"></i></a></td>
            <td ng-show="showMeridian"></td>
	    </tr>
	    <tr>
            <td class="control-group" ng-class="{'error': invalidHours}"><input type="text" ng-model="hours" ng-change="updateHours()" class="span1 text-center" ng-mousewheel="incrementHours()" ng-readonly="readonlyInput" maxlength="2"></td>
            <td>:</td>
            <td class="control-group" ng-class="{'error': invalidMinutes}"><input type="text" ng-model="minutes" ng-change="updateMinutes()" class="span1 text-center" ng-readonly="readonlyInput" maxlength="2"></td>
            <td ng-show="showMeridian"><button type="button" ng-click="toggleMeridian()" class="btn text-center">{% verbatim %}{{meridian}}{% endverbatim %}</button></td>
	    </tr>
	    <tr class="text-center">
            <td><a ng-click="decrementHours()" class="btn btn-link"><i class="fa fa-chevron-down"></i></a></td>
            <td>&nbsp;</td>
            <td><a ng-click="decrementMinutes()" class="btn btn-link"><i class="fa fa-chevron-down"></i></a></td>
            <td ng-show="showMeridian"></td>
	    </tr>
	</table>
</script>

<script type="text/ng-template" id="template/tooltip/tooltip-html-unsafe-popup.html">
	<div class="tooltip {% verbatim %}{{placement}}{% endverbatim %}" ng-class="{ in: isOpen(), fade: animation() }">
	  <div class="tooltip-arrow"></div>
	  <div class="tooltip-inner" bind-html-unsafe="content"></div>
	</div>
</script>

<script type="text/ng-template" id="template/tooltip/tooltip-popup.html">
	<div class="tooltip {% verbatim %}{{placement}}{% endverbatim %}" ng-class="{ in: isOpen(), fade: animation() }">
  		<div class="tooltip-arrow"></div>
  		<div class="tooltip-inner" ng-bind="content"></div>
	</div>
</script>

<script type="text/ng-template" id="template/typeahead/typeahead-match.html">
    <a tabindex="-1" bind-html-unsafe="match.label | typeaheadHighlight:query"></a>
</script>

<script type="text/ng-template" id="template/typeahead/typeahead-popup.html">
    <ul class="typeahead dropdown-menu" ng-style="{display: isOpen()&&'block' || 'none', top: position.top+'px', left: position.left+'px'}">
        <li ng-repeat="match in matches" ng-class="{active: isActive($index) }" ng-mouseenter="selectActive($index)" ng-click="selectMatch($index)">
            <typeahead-match index="$index" match="match" query="query" template-url="templateUrl"></typeahead-match>
        </li>
    </ul>
</script>

<script type="text/ng-template" id="template/typeahead/typeahead.html">
    <ul class="typeahead dropdown-menu" ng-style="{display: isOpen()&&'block' || 'none', top: position.top+'px', left: position.left+'px'}">
        <li ng-repeat="match in matches" ng-class="{active: isActive($index) }" ng-mouseenter="selectActive($index)">
            <a tabindex="-1" ng-click="selectMatch($index)" ng-bind-html-unsafe="match.label | typeaheadHighlight:query"></a>
        </li>
    </ul>
</script>

<script type="text/ng-template" id="itemTpl.html">
	<a tabindex="-1" href="{%verbatim%} {{match.model.url}} {%endverbatim%}">
		<span ng-switch on="match.model.type">
			<i ng-switch-when="user" class="fa fa-user"></i>
			<i ng-switch-when="package" class="fa fa-gears"></i>
			<i ng-switch-when="search" class="fa fa-search"></i>
		</span>
		<span data-ng-if="match.model.search">Buscar: </span><span ng-bind-html="match.model.name | typeaheadHighlight:query"></span>
		<span data-ng-if="match.model.username">@</span><span data-ng-if="match.model.username" ng-bind-html="match.model.username | typeaheadHighlight:query"></span>
	</a>
</script>

tribus/data/templates/footer.html
{% load i18n %}
<div id="footer">
    <div class="container-fluid">
        <div class="row-fluid">
            <span class="span5">
                <span class="row-fluid">

                    <a href="/about/terms">{% trans 'Terms of Service' %}</a>
                    &sim;
                    <a href="/about/privacy">{% trans 'Privacy Policy' %}</a>

                </span>
            </span>
            <span class="span7">
                <span class="pull-right">
                    <a href="/about">{% trans 'Tribus is Free Software' %}</a>
                </span>
            </span>
        </div>
    </div>
</div>

tribus/data/templates/tribs.html
{% load i18n %}
{% load waffle_tags %}

<div data-ng-controller="TribController" data-ng-init="addOldTribs();pollNewTribs()">
    <div class="alert-placeholder">
        <span data-alert data-ng-repeat="alert in alerts" type="alert.type" close="closeAlert($index)">
            {% verbatim %}{{ alert.msg }}{% endverbatim %}
        </span>
    </div>
    {% switch profile %}
    <div data-ng-show="template_name == 'dashboard' || template_name == 'profile'" class="action_publisher">
        <form autocomplete="off" name="action_form" data-ng-submit="createNewTrib()">
            <div class="row-fluid">
                <span class="span1">
                    <span class="action_avatar" data-ng-style="{'background-image': 'url(\''+user_gravatar+'\')'}"></span>
                </span>
                <span class="span9 action_body">
                    <span class="arrow_left"></span>
                    <span class="action_bubble">
                        <textarea data-ng-model="trib_content" id="id_trib_content" name="trib_content" class="action_textarea" cols="40" rows="2" placeholder="{% blocktrans %}What are you doing?{% endblocktrans %}"></textarea>
                        <span class="action_validation"></span>
                    </span>
                </span>
                <span class="span2">
                    <button class="btn btn-success action_button" disabled="disabled">
                        <span class="fa fa-pencil"></span>
                        {% trans 'Publish' %}
                    </button>
                </span>
            </div>
        </form>
    </div>
    <div class="trib_list" infinite-scroll="addOldTribs()" infinite-scroll-disabled="controller_busy" infinite-scroll-distance="0">
        <ul>
            <li data-ng-show="tribs.length == 0 && template_name == 'dashboard'" class="trib_intro">
                <span class="trib_body">
                    <span class="trib_title">
                        <h2>{% trans 'Welcome to Tribus!' %}</h2>
                    </span>
                    <span class="trib_content">
                        <p>{% trans 'This is the dashboard, a place where you can follow the updates of your favorite projects and partners.' %}</p>
                        <p>{% blocktrans %}Start by looking for your friends in the search bar on the top of the screen. Then, click on the Follow button in your friend's profile to start following their updates in your dashboard.{% endblocktrans %}</p>
                        <p>{% trans 'You can always come back here by clicking on the Tribus logo.' %}</p>
                    </span>
                </span>
            </li>
            <li data-ng-show="tribs.length == 0 && template_name == 'profile'" class="trib_intro">
                <span class="trib_body">
                    <span class="trib_content">
                        <p>{% blocktrans %}Hi {{ user_from_template }}, this is your profile.{% endblocktrans %}</p>
                        <p>{% blocktrans %}Start by writing something on your wall.{% endblocktrans %}</p>
                    </span>
                </span>
            </li>
            <li data-ng-show="tribs.length == 0 && template_name == 'profileView'" class="trib_intro">
                <span class="trib_body">
                    <span class="trib_content">
                        <p>{% blocktrans %}This is the profile of {{ user_from_template }}.{% endblocktrans %}</p>
                        <p>{% blocktrans %}{{ user_from_template }} has not written anything yet.{% endblocktrans %}</p>
                    </span>
                </span>
            </li>
            <li data-ng-show="tribs.length > 0" id="{% verbatim %}{{ trib.id }}{% endverbatim %}" class="row-fluid trib_item" data-ng-repeat="trib in tribs | orderBy: trib_orderby | limitTo: trib_limit_to track by trib.id">
                <span class="span2">
                    <span class="trib_avatar" data-ng-style="{'background-image': 'url(\''+trib.author_gravatar+'\')'}"></span>
                </span>
                <span class="arrow_left"></span>
                <span class="span10 trib_body">
                    <span class="trib_title">
                        <h3>
                            <a href="/profile/{% verbatim %}{{ trib.user_id.username }}{% endverbatim %}">
                                {% verbatim %}
                                {{ trib.user_id.first_name }} {{ trib.user_id.last_name }}
                                {% endverbatim %}
                            </a>
                        </h3>
                        <h4>{% verbatim %}@{{ trib.user_id.username }}{% endverbatim %}</h4>
                        <h4 class="pull-right" data-am-time-ago="trib.trib_pub_date"></h4>
                    </span>
                    <span class="trib_content" ng-bind-html="trib.trib_content"></span>
                    <span class="trib_interact">
                        <span class="pull-right" data-ng-click="toggleComments()">
                            <a href=""><span class="fa fa-chevron-down"></span>{% trans 'Comment' %}</a>
                        </span>
                        <span data-ng-if="trib.user_id.id == {{ user.id }}" data-ng-click="showDeleteModal()">
                            <a href=""><span class="icon-trash"></span>{% trans 'Delete' %}</a>
                        </span>
                    </span>
                    <span class="trib_reply">
                        <span class="comment_list" data-ng-controller="CommentController" data-ng-if="trib.coments_show" data-ng-init="this.trib_id = trib.id;addOldComments();">
                            <ul>
                                <li data-ng-if="comments.length > 0 && !comments_end" class="row-fluid comment_item">
                                    <button class="btn btn-beige btn-block btn-mini" data-ng-click="addOldComments()">
                                        {% trans 'Load more comments' %}
                                    </button>
                                </li>
                                <li id="{% verbatim %}{{ comment.id }}{% endverbatim %}" class="row-fluid comment_item" data-ng-repeat="comment in comments | orderBy: comment_orderby | limitTo: comment_limit_to track by comment.id">
                                    <span class="span1">
                                        <span class="comment_avatar" data-ng-style="{'background-image': 'url(\''+comment.author_gravatar+'\')'}"></span>
                                    </span>
                                    <span class="span11 comment_body">
                                        <span class="comment_text">
                                            <h3>
                                                <a href="/profile/{% verbatim %}{{ comment.user_id.username }}{% endverbatim %}">
                                                    {% verbatim %}
                                                    {{ comment.user_id.first_name }} {{ comment.user_id.last_name }}
                                                    {% endverbatim %}
                                                </a>
                                            </h3>
                                            <span data-ng-bind-html="comment.comment_content"></span>
                                        </span>
                                        <span data-ng-if="comment.user_id.id == {{ user.id }}" class="close"
                                        data-ng-click="showDeleteModal()">
                                            <span class="fa fa-times"></span>
                                        </span>
                                        <span class="comment_date">
                                            <h4 data-am-time-ago="comment.comment_pub_date"></h4>
                                        </span>
                                    </span>
                                </li>
                                <li class="comment_box">
                                    <form data-ng-submit="createNewComment()">
                                        <div class="row-fluid">
                                            <span class="span1">
                                                <span class="comment_avatar" data-ng-style="{'background-image': 'url(\''+comment_gravatar+'\')'}"></span>
                                            </span>
                                            <span class="span9 comment_body">
                                                <span class="arrow_left"></span>
                                                <span class="comment_bubble">
                                                    <textarea data-ng-model="comment_content" id="id_comment_content" name="comment_content" class="comment_textarea" cols="40" rows="1" placeholder="{% blocktrans %}What do you want to say?{% endblocktrans %}"></textarea>
                                                    <span class="comment_validation"></span>
                                                </span>
                                            </span>
                                            <span class="span2">
                                                <button class="btn btn-success btn-xs comment_button" disabled="disabled">
                                                    {% trans 'Comment' %}
                                                </button>
                                            </span>
                                        </div>
                                    </form>
                                </li>
                            </ul>
                        </span>
                    </span>
                </span>
            </li>
        </ul>
    </div>
    <script type="text/ng-template" id="delete_modal_template.html">
        <div class="modal-body">
            <button type="button" class="close" data-ng-click="cancel()">
                <span class="fa fa-times"></span>
            </button>
            <h4>{% trans 'Are you sure you want to delete this message?' %}</h4>
        </div>
        <div class="modal-footer">
            <button class="btn" data-ng-click="cancel()">
                {% trans 'Cancel' %}
            </button>
            <button class="btn btn-success" data-ng-click="ok()">
                {% trans 'Delete message' %}
            </button>
        </div>
    </script>
	{% else %}
	<div>
		<span class="trib_body">
            <span class="trib_title">
                <h2>{% trans 'Welcome to Tribus!' %}</h2>
            </span>
            <span class="trib_content">
                <p>{% trans 'This is the dashboard, a place where you can follow the updates of your projects.' %}</p>
                <p>{% trans 'You can always come back here by clicking on the Tribus logo.' %}</p>
            </span>
        </span>
	</div>
	{% endswitch %}
</div>